name: Front CI

on:
  push:
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Verificar se app inicia
      run: npm start &
